services:
  study_web:
    build: .
    # command: bash -c "bundle install && rails s -b 0.0.0.0 -p 3100"
    command: bash -lc "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -b 0.0.0.0 -p 3100"
    ports:
      - "3100:3100"  # Railsを3100で起動
    volumes:
      - ./myapp:/myapp
    working_dir: /myapp
    depends_on:
      - db
      - solr
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: development_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  solr:
    image: solr:8.11
    container_name: solr
    ports:
      - "8984:8983"
    volumes:
      - ./solr:/var/solr
    command: >
      bash -c "
        precreate-core round1 &&
        precreate-core round2 &&
        precreate-core round3 &&
        solr-foreground
      "
volumes:
  db_data: